on:
    push:
    workflow_dispatch:
    schedule:
      # Run this daily at 2400 UTC
      - cron: '0 0 * * *'

jobs:
    regular:
      continue-on-error: true
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.13-dev, 3.14-dev]
      name: regular
      steps:
        - uses: actions/checkout@v2
        - uses: deadsnakes/action@v3.2.0
          with:
            python-version: ${{ matrix.python-version }}
            nogil: true
        - run: python --version
        - run: python -m pip install --upgrade pip
        - run: chmod +x build.sh
        - run: ./build.sh
        - run: pytest --cov-append -s -v

    tsan:
      continue-on-error: true
      runs-on: ubuntu-latest
      container:
          image: ghcr.io/nascheme/cpython-tsan:${{ matrix.python-version }}
          options: --shm-size=2g
      strategy:
        matrix:
          python-version: [3.13t, 3.14t-dev]
      name: tsan
      steps:
        - uses: actions/checkout@v2
        - run: python --version
        - run: python -m pip install --upgrade pip
        - run: chmod +x build.sh
        - run: ./build.sh
        - run: python -m pytest --cov-append -s -v

